### ISSUE TITLE
Au sujet des résumés des posts... Excerpt or not excerpt ?

### ISSUE THREAD

**Issue by GrCOTE7** [bestmomo/sillo#5]
*Hi, all,*

Situation Actuelle :
-	On a un champs ‘excerpt’, à priori sensé contenir un résumé du post.  (Intéressant si l’on souhaite un résumé différent du body du post)
-	Génère un choix à faire car :
      o	Le seeder génère bel et bien un ensemble de 4 paragraphes pour ce champs, et donc body <> excerpt
      o	Mais :
           	si on édit le post, il sera rempli du début du post
           	Et de toutes façons,  dans le form, pas d’édition du excerpt, et au final, un simple…:
           
               Edit.blade.php (Ligne 118) :
                   // Mise à jour du post
                   $this->post->update($data + [
                      'category_id' => $this->category_id,
                      'excerpt'        => Str::limit($this->body, 300),
                    ]);

Situation Proposée :
-	Suppression complète du champs excerpt dans la migration, et le seeder fera ce que fait l’édition.
Au passage, en seed, comme en usage (édition), le résumé sera affiché en finissant par ‘ … ‘, et si le post est très court, par un simple  ‘.’ . Le bouton lire alors plus utile, ne sera plus affiché, sauf si l’user a le droit de modifier, ce qu’afficherait alors ce bouton.

Rien de compliqué dans tout cela, mais un véritable choix à faire :
-	Garder ce champs, et tout faire pour qu’il ait un réel intérêt, et la possibilité de l’éditer aussi
-	Ou « l’oublier », et uniquement lors de l’affichage, couper et ponctuer de la façon ad’hoc.

(Perso, je préfère cette dernière option, qui est + logique: On continue réellement dans le ‘show’ ce qu’on a déjà commencé de lire, et aussi pas de problème pour avoir un résumé cohérent, qui ne serait alors plus que le début du body du post. De même, moins de place dans la BdD d’infos qui feraient quasi doublons, car la flème sera tentante de copier/coller soi-même le début du post en création et édition…)

Le débat est ouvert…

@++

**Comment by bestmomo** [comment]
Salut,

En fait au départ j'avais prévu un contrôle pour l'éditer, puis je me suis dit que prendre le début de l'article faisait très bien l'affaire. j'airais effectivement dû faire suive le seeder pour le réalisme de la génération.

Par contre, supprimer ce champ dans la base pose un problème. Dans l'affichage de la page d'accueil, on a six cadres (ou plus si on veut) avec des résumés des articles. Si le champ n'existe pas, il faut charger l'intégralité des contenus pour générer cette partie, ce qui est lourd au niveau manipulation des données avec des articles qui peuvent être conséquents.

**Comment by GrCOTE7** [comment]
Re,


Oui, je comprends maintenant mieux l'intérêt premier de ce 'excerpt'...
Car là, c'est un argument de poids (C'est le cas de le dire ! ;-) )

Cependant, il me semble alors qu'il doit être possible de récupérer les posts dont on a besoin dans la page, en coupant immédiatement la 'longeur' nécessaire pour le résumé/courte description nécessaire dans la page d'accueil 
(Quitte à, juste pour ce cas, utiliser le Query Builder au détriment d'Eloquent si pratique... Avec une fonction de rappel), non ?

Un truc style:
```
$posts = DB::table('posts')
            ->paginate(POSTS_PER_PAGE)
            ->transform(function ($post) {
                $post->content = substr($post->content, 0, 300).'...';
                return $post;
            });
```
(Autre piste: Faire une Vue SQL style:
```
CREATE VIEW short_posts AS
SELECT id, title, CONCAT(SUBSTR(content, 1, 300), '...') as content
FROM posts;
```
Puis:
```
$posts = DB::table('short_posts')->paginate(POSTS_PER_PAGE);
```
)

Si vraiment à terme, 'excerpt' a rapidement, soit ne continent que le début de 'content', ces voies me semblent intéressantes ;-)

Maintenant, si en fait, ce excerpt devient un champs nommé 'description', oui, là, il me semble intéressant de le garder car en ce cas, il a vraiment un autre rôle que celui de n'être que le début du post, et me semble + être dans le sens de ce que tu souhaites obtenir, n'est-ce pas :-) ?

**Comment by bestmomo** [comment]
j'aime les solutions simples, pourquoi pas ça ?
```
protected function getBaseQuery(): Builder
{
    return Post::select(
                'id',
                'slug',
                'image',
                'title',
                DB::raw('SUBSTRING(body, 1, 300) AS excerpt'),
                'user_id',
                'category_id',
                'serie_id',
                'created_at'
            )
            ->with('user:id,name', 'category', 'serie')
            ->whereActive(true)
            ->latest();
}
```

**Comment by GrCOTE7** [comment]
Oui, "tout bêtement" ;-) 

ça le fait ! :-)

**Comment by GrCOTE7** [comment]
(On peut clôturer cette 'Issue'... ;-) Quitte à la re-ouvrir + tard si besoin :-) )
